/* Auto-generated from Bandcamp metadata (see ADMIN.md).
   "bonus:true" = track added on Bandcamp after the original release.
   NOTE: 'Emotional Piano' (Humanity is a Beast, old track 9) was dropped from
   Bandcamp and has no file here — drop an mp3 into music/humanity-is-a-beast/
   and add it to tracks[] if you have the master. */
window.ALBUMS = [
  {
    slug: 'humanity-is-a-beast',
    title: "Humanity is a Beast",
    year: 2015,
    art: 'covers/humanity-is-a-beast.jpg',
    bandcamp: 'https://aenite.bandcamp.com/album/humanity-is-a-beast',
    tracks: [
      { file: 'music/humanity-is-a-beast/01-labyrinth.mp3', title: "Labyrinth", dur: 157 },
      { file: 'music/humanity-is-a-beast/02-humanity-is-a-beast.mp3', title: "Humanity is a Beast", dur: 94 },
      { file: 'music/humanity-is-a-beast/03-resent.mp3', title: "Resent", dur: 83 },
      { file: 'music/humanity-is-a-beast/04-8bitty.mp3', title: "8bitty", dur: 115 },
      { file: 'music/humanity-is-a-beast/05-absolutely-8bit.mp3', title: "Absolutely 8bit", dur: 92 },
      { file: 'music/humanity-is-a-beast/06-sustaining.mp3', title: "Sustaining", dur: 175 },
      { file: 'music/humanity-is-a-beast/07-broken.mp3', title: "Broken", dur: 205 },
      { file: 'music/humanity-is-a-beast/08-desolate.mp3', title: "Desolate", dur: 89 },
    ]
  },
  {
    slug: 'eigengrau',
    title: "Eigengrau",
    year: 2012,
    art: 'covers/eigengrau.jpg',
    bandcamp: 'https://aenite.bandcamp.com/album/eigengrau',
    tracks: [
      { file: 'music/eigengrau/01-eigengrau.mp3', title: "Eigengrau", dur: 153 },
      { file: 'music/eigengrau/02-i-guess-this-is-it.mp3', title: "I Guess This Is It", dur: 133 },
      { file: 'music/eigengrau/03-this-isn-t-it.mp3', title: "This Isn't It", dur: 122 },
      { file: 'music/eigengrau/04-battle-base.mp3', title: "Battle Base", dur: 63 },
      { file: 'music/eigengrau/05-how-can-i.mp3', title: "How Can I", dur: 165 },
      { file: 'music/eigengrau/06-help.mp3', title: "Help", dur: 152 },
    ]
  },
  {
    slug: 'little-banger',
    title: "Little Banger",
    year: 2012,
    art: 'covers/little-banger.jpg',
    bandcamp: 'https://aenite.bandcamp.com/album/little-banger',
    tracks: [
      { file: 'music/little-banger/01-party-crasher.mp3', title: "Party Crasher", dur: 137 },
      { file: 'music/little-banger/02-action-one.mp3', title: "Action One", dur: 95 },
      { file: 'music/little-banger/03-sketchy-memory.mp3', title: "Sketchy Memory", dur: 117 },
      { file: 'music/little-banger/04-looking-into-the-void.mp3', title: "Looking Into The Void", dur: 63 },
      { file: 'music/little-banger/05-burnt-candles.mp3', title: "Burnt Candles", dur: 83 },
      { file: 'music/little-banger/06-drum-beat-things.mp3', title: "Drum Beat Things", dur: 70 },
      { file: 'music/little-banger/07-entitled-drop.mp3', title: "Entitled Drop", dur: 73 },
      { file: 'music/little-banger/08-a-minute-in-limbo.mp3', title: "A Minute In Limbo", dur: 100 },
      { file: 'music/little-banger/09-quick-trains.mp3', title: "Quick Trains", dur: 74 },
      { file: 'music/little-banger/10-back-to-the-90s.mp3', title: "Back to the 90s", dur: 69, bonus: true },
      { file: 'music/little-banger/11-uprising.mp3', title: "Uprising", dur: 88 },
      { file: 'music/little-banger/12-underrocking.mp3', title: "Underrocking", dur: 30 },
      { file: 'music/little-banger/13-7-by-8.mp3', title: "7 by 8", dur: 94 },
      { file: 'music/little-banger/14-dethroned.mp3', title: "Dethroned", dur: 84 },
      { file: 'music/little-banger/15-sketchy-action-like-the-void.mp3', title: "Sketchy Action Like The Void", dur: 56, bonus: true },
    ]
  },
  {
    slug: 'nauleadew',
    title: "Nauleadew",
    year: 2012,
    art: 'covers/nauleadew.jpg',
    bandcamp: 'https://aenite.bandcamp.com/album/nauleadew',
    tracks: [
      { file: 'music/nauleadew/01-nauleadew.mp3', title: "Nauleadew", dur: 142 },
      { file: 'music/nauleadew/02-atwain.mp3', title: "Atwain", dur: 108 },
      { file: 'music/nauleadew/03-me-you-them-and-us.mp3', title: "Me You Them And Us", dur: 98 },
      { file: 'music/nauleadew/04-let-everything-crumble-to-dust.mp3', title: "Let Everything Crumble To Dust", dur: 116 },
      { file: 'music/nauleadew/05-fence-on-stairs.mp3', title: "Fence On Stairs", dur: 111 },
      { file: 'music/nauleadew/06-a-day-to-forget.mp3', title: "A Day To Forget", dur: 149 },
      { file: 'music/nauleadew/07-norwind.mp3', title: "Norwind", dur: 60 },
      { file: 'music/nauleadew/08-intro.mp3', title: "Intro", dur: 87 },
      { file: 'music/nauleadew/09-lor.mp3', title: "Lor", dur: 140 },
      { file: 'music/nauleadew/10-looking-for-a-ramp.mp3', title: "Looking For A Ramp", dur: 115 },
      { file: 'music/nauleadew/11-when-the-minute-strikes.mp3', title: "When The Minute Strikes", dur: 124, bonus: true },
      { file: 'music/nauleadew/12-a-rough-dream.mp3', title: "A Rough Dream", dur: 96 },
      { file: 'music/nauleadew/13-bard.mp3', title: "Bard", dur: 73 },
      { file: 'music/nauleadew/14-moonflame2000.mp3', title: "Moonflame2000", dur: 86 },
      { file: 'music/nauleadew/15-sleeping-samba.mp3', title: "Sleeping Samba", dur: 159 },
      { file: 'music/nauleadew/16-speed-challenge.mp3', title: "Speed Challenge!", dur: 70 },
      { file: 'music/nauleadew/17-the-beat-clock.mp3', title: "The Beat Clock", dur: 117 },
      { file: 'music/nauleadew/18-file-not-found-even-though-i-looked-so-hard.mp3', title: "File Not Found Even Though I Looked So Hard", dur: 58 },
    ]
  },
  {
    slug: 'scary-lines',
    title: "Scary Lines",
    year: 2012,
    art: 'covers/scary-lines.jpg',
    bandcamp: 'https://aenite.bandcamp.com/album/scary-lines',
    tracks: [
      { file: 'music/scary-lines/01-tune.mp3', title: "Tune", dur: 147 },
      { file: 'music/scary-lines/02-draft-1.mp3', title: "Draft #1", dur: 83 },
      { file: 'music/scary-lines/03-doc.mp3', title: "Doc", dur: 118 },
      { file: 'music/scary-lines/04-8-bit-skies.mp3', title: "8-Bit Skies", dur: 110 },
      { file: 'music/scary-lines/05-a-combination.mp3', title: "A Combination", dur: 78 },
      { file: 'music/scary-lines/06-the-sarlacc-pit.mp3', title: "The Sarlacc Pit", dur: 140 },
      { file: 'music/scary-lines/07-scary-jazz-that-turns-into-electronic.mp3', title: "Scary Jazz That Turns Into Electronic", dur: 49 },
      { file: 'music/scary-lines/08-various-flutes-creating-chords.mp3', title: "Various Flutes Creating Chords", dur: 75 },
      { file: 'music/scary-lines/09-technobabble.mp3', title: "Technobabble", dur: 84 },
      { file: 'music/scary-lines/10-8-bit-happy-song.mp3', title: "8-Bit Happy Song", dur: 113 },
      { file: 'music/scary-lines/11-this-is-very-bad-i-m-sorry.mp3', title: "This Is Very Bad I'm Sorry", dur: 62 },
    ]
  },
  {
    slug: 'starting-again',
    title: "Starting Again",
    year: 2012,
    art: 'covers/starting-again.jpg',
    bandcamp: 'https://aenite.bandcamp.com/album/starting-again',
    tracks: [
      { file: 'music/starting-again/01-91.mp3', title: "91", dur: 161 },
      { file: 'music/starting-again/02-comp-song-1.mp3', title: "Comp Song #1", dur: 185 },
      { file: 'music/starting-again/03-careful-with-that-bass.mp3', title: "Careful with that Bass", dur: 200 },
      { file: 'music/starting-again/04-floating-bed-instrumental.mp3', title: "Floating Bed Instrumental", dur: 109 },
      { file: 'music/starting-again/05-have-a-wheel-instrumental.mp3', title: "Have A Wheel Instrumental", dur: 107 },
      { file: 'music/starting-again/06-something-i-made-in-30-minutes.mp3', title: "Something I Made in 30 Minutes", dur: 90, bonus: true },
      { file: 'music/starting-again/07-comp-song-2.mp3', title: "Comp Song #2", dur: 161 },
      { file: 'music/starting-again/08-early-run.mp3', title: "Early Run", dur: 163 },
      { file: 'music/starting-again/09-anxiety.mp3', title: "Anxiety", dur: 222 },
      { file: 'music/starting-again/10-careful-of-that-cactus-wolfie-instrumental.mp3', title: "Careful of that Cactus Wolfie Instrumental", dur: 100 },
      { file: 'music/starting-again/11-can-t-get-up.mp3', title: "Can't Get Up", dur: 94 },
    ]
  },
  {
    slug: 'some-and-others',
    title: "Some and Others",
    year: 2026,
    art: 'covers/some-and-others.jpg',
    bandcamp: 'https://aenite.bandcamp.com/album/some-and-others',
    tracks: [
      { file: 'music/some-and-others/01-some-and-others.mp3', title: "Some and Others", dur: 125 },
      { file: 'music/some-and-others/02-bard-2.mp3', title: "Bard 2", dur: 58 },
      { file: 'music/some-and-others/03-classic.mp3', title: "Classic", dur: 96 },
      { file: 'music/some-and-others/04-martians-are-benevolent.mp3', title: "Martians are Benevolent", dur: 96 },
      { file: 'music/some-and-others/05-failboat103.mp3', title: "Failboat103", dur: 76 },
      { file: 'music/some-and-others/06-people.mp3', title: "People", dur: 136 },
      { file: 'music/some-and-others/07-forgive-me.mp3', title: "Forgive Me", dur: 46 },
      { file: 'music/some-and-others/08-until-you-wait.mp3', title: "Until You Wait", dur: 133 },
      { file: 'music/some-and-others/09-8bit-pop.mp3', title: "8Bit Pop", dur: 45 },
      { file: 'music/some-and-others/10-what-no.mp3', title: "What No", dur: 44 },
      { file: 'music/some-and-others/11-who-asked-you.mp3', title: "who asked you", dur: 78 },
      { file: 'music/some-and-others/12-something-fruity.mp3', title: "Something Fruity", dur: 23 },
    ]
  },
];
